// EPOS RISC-V 32 PMU Mediator

#include <architecture/rv32/rv32_pmu.h>

__BEGIN_SYS

const RV32_PMU::Event RV32_PMU::_events[EVENTS] = {
    TIME,                                       // CPU_CYCLES
    CYCLES,                                     // UNHALTED_CYCLES

    INSTRUCTIONS_RETIRED,                       // INSTRUCTIONS_RETIRED
    INTEGER_LOAD_INSTRUCTIONS_RETIRED,          // LOAD_INSTRUCTIONS_RETIRED
    INTEGER_STORE_INSTRUCTIONS_RETIRED,         // STORE_INSTRUCTIONS_RETIRED
    INTEGER_ARITHMETIC_INSTRUCTIONS_RETIRED,    // INTEGER_ARITHMETIC_INSTRUCTIONS_RETIRED
    INTEGER_MULTIPLICATION_INSTRUCTIONS_RETIRED,// INTEGER_MULTIPLICATION_INSTRUCTIONS_RETIRED
    INTEGER_DIVISION_INSTRUCTIONS_RETIRED,      // INTEGER_DIVISION_INSTRUCTIONS_RETIRED
    UNSUPORTED_EVENT,                           // FPU_INSTRUCTIONS_RETIRED
    UNSUPORTED_EVENT,                           // SIMD_INSTRUCTIONS_RETIRED
    ATOMIC_MEMEMORY_INSTRUCTIONS_RETIRED,       // ATOMIC_MEMEMORY_INSTRUCTIONS_RETIRED

    UNSUPORTED_EVENT,                           // BRANCHES
    CONDITIONAL_BRANCHES_RETIRED,               // CONDITIONAL_BRANCHES
    UNSUPORTED_EVENT,                           // PREDICTABLE_BRANCHES
    UNSUPORTED_EVENT,                           // IMIDIATE_BRANCHES
    BRANCH_JUMP_TARGET_MISPREDICTION,           // BRANCH_MISPREDICTIONS
    BRANCH_DIRECTION_MISPREDICTION,             // BRANCH_DIRECTION_MISPREDICTIONS

    EXCEPTIONS_TAKEN,                           // EXCEPTIONS
    UNSUPORTED_EVENT,                           // INTERRUPTS

    UNSUPORTED_EVENT,                           // L1_CACHE_HITS
    UNSUPORTED_EVENT,                           // L1_CACHE_MISSES
    UNSUPORTED_EVENT,                           // L1_DATA_CACHE_MISSES
    UNSUPORTED_EVENT,                           // L1_DATA_CACHE_WRITEBACKS
    INSTRUCTION_CACHE_MISS,                     // L1_INSTRUCTION_CACHE_MISSES
    UNSUPORTED_EVENT,                           // L2_CACHE_HITS
    UNSUPORTED_EVENT,                           // L2_CACHE_MISSES
    UNSUPORTED_EVENT,                           // L2_DATA_CACHE_MISSES
    UNSUPORTED_EVENT,                           // L2_DATA_CACHE_WRITEBACKS
    UNSUPORTED_EVENT,                           // L3_CACHE_HITS
    UNSUPORTED_EVENT,                           // L3_CACHE_MISSES
    UNSUPORTED_EVENT,                           // INSTRUCTION_MEMORY_ACCESSES
    UNSUPORTED_EVENT,                           // UNCACHED_MEMORY_ACCESSES
    UNSUPORTED_EVENT,                           // UNALIGNED_MEMORY_ACCESSES

    UNSUPORTED_EVENT,                           // BUS_CYCLES
    UNSUPORTED_EVENT,                           // BUS_ACCESSES
    UNSUPORTED_EVENT,                           // TLB_MISSES
    UNSUPORTED_EVENT,                           // INSTRUCTION_TLB_MISSES
    UNSUPORTED_EVENT,                           // MEMORY_ERRORS

    UNSUPORTED_EVENT,                           // STALL_CYCLES
    UNSUPORTED_EVENT,                           // STALL_CYCLES_CACHE
    UNSUPORTED_EVENT,                           // STALL_CYCLES_DATA_CACHE
    UNSUPORTED_EVENT,                           // STALL_CYCLES_TLB
    UNSUPORTED_EVENT,                           // STALL_CYCLES_MEMORY
    UNSUPORTED_EVENT,                           // PIPELINE_SERIALIZATIONS
    UNSUPORTED_EVENT,                           // BUS_SERIALIZATION

    SYSTEM_INSTRUCTIONS_RETIRED,                // ARCHITECTURE_DEPENDENT_EVENT45
    JAL_INSTRUCTIONS_RETIRED,                   // ARCHITECTURE_DEPENDENT_EVENT46
    JALR_INSTRUCTIONS_RETIRED,                  // ARCHITECTURE_DEPENDENT_EVENT47
    LOAD_USE_INTERLOCK,                         // ARCHITECTURE_DEPENDENT_EVENT48
    LONG_LATENCY_INTERLOCK,                     // ARCHITECTURE_DEPENDENT_EVENT49
    CSR_READ_INTERLOCK,                         // ARCHITECTURE_DEPENDENT_EVENT50
    INSTRUCTION_CACHE_ITIM_BUSY,                // ARCHITECTURE_DEPENDENT_EVENT51
    DATA_CACHE_DTIM_BUSY,                       // ARCHITECTURE_DEPENDENT_EVENT52
    PIPELINE_FLUSH_FROM_CSR_WRITE,              // ARCHITECTURE_DEPENDENT_EVENT53
    PIPELINE_FLUSH_FROM_OTHER_EVENT,            // ARCHITECTURE_DEPENDENT_EVENT54
    INTEGER_MULTIPLICATION_INTERLOCK            // ARCHITECTURE_DEPENDENT_EVENT55
};

__END_SYS
